language: node_js
node_js:
  - node
script:
  - npm run test
before_deploy:
  - npm run build
  - rm -rf node_modules
  # - source ./.travis/s3_utils.sh
  # - S3_BUCKET=$(get_s3_bucket)
  # - echo "Will push to S3 bucket $S3_BUCKET."
deploy:
  - provider: npm
    email: "phillypackage@gmail.com"
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    on:
      tags: true
env:
