name: Node test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10,x
      uses: actions/setup-node@v1
    - name: npm install, build, and test
      run: |
        npm install
        npm test
      env:
        CI: true
